### PR TITLE
Added stroke option

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
Hi there,

I needed a stroke option for one svg, so I added it similar to the fill option.

Have a nice day!

### CODE REVIEW

**Comment by MoOx** [comment]
Nice!
Can you add a minimal test about this?
Something similar to this https://github.com/MoOx/react-svg-inline/blob/35fd861293aa299ccacadf46d127a35c3ae72161/src/__tests__/index.js#L118-L126
Btw it would be awesome if you add it for fill too ^^

**Comment by DanielMSchmidt** [comment]
yeah, will do this soon, thanks for the fast feedback ;)

**Comment by sample-usr** [comment]
Any update on this?

**Comment by DanielMSchmidt** [comment]
Sorry, I have no time for this currently, I am really sorry :(

**Pull request closed without merging**
